myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView,
    ProfileView

)    

urlpatterns = [
    path('',BaseView.as_view(), name= 'base'),
    path('product/<str:ct_model>/<str:slug>',ProductDetailView.as_view(), name= 'product_detail'),
    path('product/<str:slug>',CategoryDetailView.as_view(), name= 'category_detail'),
    path('cart/',CartView.as_view(), name= 'cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>',AddToCartView.as_view(), name= 'add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>',DeleteFromCartView.as_view(), name= 'delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>',ChangeQTYView.as_view(), name= 'change_qty'),
    path('checkout/',CheckoutView.as_view(), name= 'checkout'),
    path('make-order/',MakeOrderView.as_view(), name= 'make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

shop/models.py
import sys
from PIL import Image
from django.conf.urls import url

from django.core import exceptions
from django.db import models
from django.contrib.auth import  get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse
from django.utils import timezone

from io import BytesIO

User = get_user_model()

def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]

def get_product_url(obj,view_name):
    ct_model = obj.__class__._meta.model_name
    return reverse(view_name, kwargs={'ct_model':ct_model,'slug':obj.slug})

class MinResolutionErrorException(Exception):
    pass

class MaxResolutionErrorException(Exception):
    pass

class LatestProductManager:
    @staticmethod
    def get_products_for_main_page(*args,**kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_product = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_product)
        if with_respect_to:
            ct_models = ContentType.objects.filter(model=with_respect_to)  
            if ct_models.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )     
        return products

class LatestProducts:
    object = LatestProductManager()

class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки':'notebook__count',
        'Смартфоны':'smartphone__count',
        'Аксессуары':'accessories__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook','smartphone','accessories')
        print('models:' ,models)
        qs = list(self.get_queryset().annotate(*models))
        print('get_queryset:',qs)
        data = [
            dict(name=c.name,url=c.get_absolute_url(),count=getattr(c,self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data

# Категория товаров
class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug':self.slug})

# Товары
class Product(models.Model):

    MIN_RESOLUTION = (400,400)
    MAX_RESOLUTION = (500,500)
    MAX_IMAGE_SIZE = 3145728 #3 MB in bytes

    class Meta:
        abstract = True

    category = models.ForeignKey(Category,verbose_name='Категория',on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(null=True,verbose_name='Описание')
    price = models.DecimalField(max_digits=9,decimal_places=2,verbose_name='Цена')

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        # image = self.image  
        # img = Image.open(image)
        # min_height, min_width = self.MIN_RESOLUTION
        # max_height, max_width = self.MAX_RESOLUTION
        # if img.height < min_height or img.width < min_width:
        #     raise MinResolutionErrorException('Разрешение изображения меньше минимального')
        # if img.height > max_height or img.width > max_width:
        #     raise MaxResolutionErrorException('Разрешение изображения больше максимального')    
        
        image = self.image  
        img = Image.open(image)
        new_img = img.convert('RGB')
        if img.size[0] > img.size[1]:
            w_percent = (self.MAX_RESOLUTION[0] / float(img.size[0]))
            h_size = int((float(img.size[1]) * float(w_percent)))
            resized_new_img = new_img.resize((self.MAX_RESOLUTION[0], h_size), Image.ANTIALIAS)
        else:
            w_percent = (self.MAX_RESOLUTION[1] / float(img.size[1]))
            h_size = int((float(img.size[0]) * float(w_percent)))
            resized_new_img = new_img.resize((h_size,self.MAX_RESOLUTION[1]), Image.ANTIALIAS)    
            
        filestream = BytesIO()
        resized_new_img.save(filestream,'JPEG',quality = 90)
        filestream.seek(0)
        name = '{}.{}'.format(*self.image.name.split('.'))
        self.image = InMemoryUploadedFile(
            filestream,'ImageField',name,'jpeg/image',sys.getsizeof(filestream),None
        )
        super().save(*args,**kwargs) 

    def get_model_name(self):
        return self.__class__.__name__.lower()    

class Notebook(Product):
    diagonal = models.CharField(max_length=255,verbose_name='Диагональ')
    display_type = models.CharField(max_length=255,verbose_name='Тип дисплея')
    processor_freg = models.CharField(max_length=255,verbose_name='Частота процессора')
    ram = models.CharField(max_length=255,verbose_name='Оперативная память')
    video = models.CharField(max_length=255,verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255,verbose_name='Время работы аккумулятора')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self,'product_detail')        

class Smartphone(Product):
    diagonal = models.CharField(max_length=255,verbose_name='Диагональ')
    display_type = models.CharField(max_length=255,verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255,verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=255,verbose_name='Объем батареи')
    ram = models.CharField(max_length=255,verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие CD карты')
    sd_volume_max = models.CharField(max_length=255,null=True,blank=True,verbose_name='Максимальный объем встраиваемой памяти')
    main_cam_mp = models.CharField(max_length=255,verbose_name='Камера (МП)')
    frontal_cam_mp = models.CharField(max_length=255,verbose_name='Фронтальная камера (МП)')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)   

    def get_absolute_url(self):
        return get_product_url(self,'product_detail') 

class Accessories(Product):

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)   

    def get_absolute_url(self):
        return get_product_url(self,'product_detail')                 

# Товары в корзине
class CartProduct(models.Model):
    user = models.ForeignKey('Customer',verbose_name='Покупатель',on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart',verbose_name='Корзина',on_delete=models.CASCADE,related_name='related_products')
    
    content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type','object_id')

    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9,decimal_places=2,verbose_name='Общая цена')

    def __str__(self):
        return 'Продукт: {} (для корзины)'.format(self.content_object.title)        

    def save(self,*args,**kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args,**kwargs) 

# Корзина
class Cart(models.Model):
    owner = models.ForeignKey('Customer',null=True,verbose_name='Владелец',on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct,blank=True,related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9,default=0,decimal_places=2,verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id) 

# Покупатели
class Customer(models.Model):
    user = models.ForeignKey(User,verbose_name='Пользователь',on_delete=models.CASCADE)
    phone = models.CharField(max_length=20,verbose_name='Номер телефона',null=True,blank=True)
    address = models.CharField(max_length=1024,verbose_name='Адрес',null=True,blank=True)
    orders = models.ManyToManyField('Order',verbose_name='Заказы покупателя',related_name='related_customer')

    def __str__(self):
        return 'Покупатель: {} {}'.format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW,'Новый заказ'),
        (STATUS_IN_PROGRESS,'Заказ в обработке'),
        (STATUS_READY,'Заказ готов'),
        (STATUS_COMPLETED,'Заказ выполнен'),
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка'),
    )

    customer = models.ForeignKey(Customer,verbose_name='Покупатель',on_delete=models.CASCADE,related_name='related_orders')
    cart = models.ForeignKey(Cart,verbose_name='Корзина',on_delete=models.CASCADE,null=True,blank=True)
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    phone = models.CharField(max_length=20,verbose_name='Номер телефона',null=True,blank=True)
    address = models.CharField(max_length=1024,verbose_name='Адрес',null=True,blank=True)
    status = models.CharField(

shop/forms.py
from django import forms
from django import forms
from django.contrib.contenttypes import fields
from django.contrib.auth import get_user_model
from django.forms import widgets

from .models import Order

User = get_user_model()

class OrderForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name','last_name','phone','address','buying_type','order_date','comment'
        )

class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином "{username} не найден в системе')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(
                f'Регистрация для домена {domain} невозможна'
            )
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                f'Данный почтовый адрес уже зарегистрирован в системе'
            )
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                f'Имя {username} занято'
            )
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']

shop/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click',function(){
        if($('#id_sd').prop('checked')==true){
            $('#id_sd_volume_max').prop('readonly',false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background','white')
        }else{
            $('#id_sd_volume_max').prop('readonly',true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background','lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title >Магазин электротехники</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">
</head>
<style>
    body {
      padding-top: 76px;
    }
</style>
<body >


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="background-image: url('/static/first_bg.jpg'); background-color: #10569c!important" >
    <div class="container" >
      <a class="navbar-brand" href="{% url 'base' %}" > <strong style="font-size: 30px;color: rgb(182, 243, 13);">Магазин Электротехники</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive"  >
        <ul class="navbar-nav ml-auto">
          <ul class="navbar-nav">
            {% if not request.user.is_authenticated %}
          <li>
            <a class="nav-link text-white" href="{% url 'login' %}"><strong>АВТОРИЗАЦИЯ</strong></a> 
          </li>
            <li>
            <a class="nav-link text-white" href="{% url 'registration' %}"><strong>РЕГИСТРАЦИЯ</strong></a>
          </li>
          {% else %}
              <li class="nav-item" style="font-size: 20px;">
                {% if request.user.is_authenticated %}
                  <span class="navbar text text-light">Здравствуйте,
                    <span class="badge badge-danger">
                      <a href="{% url 'profile' %}" style="text-decoration: none; font-size: 14px; color: white;">{{ request.user.username }}</a>
                    </span>
                    | <a href="{% url 'logout' %}" style="color: rgb(182, 243, 13); text-decoration: None;">Выйти</a>
                  </span>
               {% endif %}
              </li>
          {% endif %}
          </ul>
          
          
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger"> {{ cart.products.count }}</span></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Корзина<span class="badge badge-pill badge-danger">0</span></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container" >

    <div class="row">

      <div class="col-lg-3 mt-5">
        <h1 class="my-4">Категории</h1>
        <div class="list-group" >
          {% for category in categories %}
          <a href="{{ category.url }}" class="list-group-item" style="font-size: 20px;">{{ category.name }} ({{ category.count }}) </a>
          {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9" >
        {% block content %}
        <!-- <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div> -->

        <nav aria-label="breadcrumb" class="mt-3" >
          <ol class="breadcrumb" style="background-color: rgb(6, 164, 226)!important;  text-align: center" >
              <li class="breadcrumb-item" style="font-size: 25px;; color: white;"> <strong > Товары в магазине </strong></li>
          </ol>
        </nav>

        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img style="width: auto; max-height: 150px"  class="card-img-top rounded mx-auto d-block" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} руб.</h5>
                {% if request.user.is_authenticated %}
                <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                  <button class="btn btn-danger">Добавить в корзину</button>
                </a>
                {% else %}
                  <a href="{% url 'login' %}"> 
                    <button class="btn btn-danger">Добавить в корзину</button>
                  </a>
                {% endif %}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->

        {% endblock content %}  
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; TMS/45 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

shop/templates/cart.html
{% extends 'base.html' %} 

{% block content %}   

<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
{% if messages %}
  {% for message in messages %}  
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true" >&times; </span>
    </button>
  </div>
  {% endfor %}
{% endif %}

{% if cart.products.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
      <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
      {% for item in cart.products.all %}
      <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class='w-25'><img src="{{ item.content_object.image.url }}" class = 'img-fluid' ></td>
          <td>{{ item.content_object.price }} руб.</td>
          <td>
            <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="POST">
              {% csrf_token %}
              <input type="number" class ="form-control" name='qty' style="width: 70px;" min = "1" value="{{ item.qty }}">
              <br>
              <input type="submit" class="btn btn-primary" value="Изменить кол-во">
            </form>
          </td>
          <td>{{ item.final_price }} руб.</td>
          <td>
            <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
          </td>
      </tr>
      {% endfor %}
      <tr>
        <td colspan="2"> </td>
        <td>Итого:</td>
        <td>{{ cart.total_products }} </td>
        <td><strong>{{ cart.final_price }} руб.</strong></td>
        <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
    </tr>
  </tbody>
</table>
  
{% endif %}
  
{% endblock content %}

shop/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 200px; margin-top: 160px">
<div class="col-md-6 offset-md-3">
    <h3 class="text-center">Авторизация</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block" value="Войти">
        
    </form>
    <a class="nav-link text-white" href="{% url 'registration' %}">
        <button class="btn btn-success btn-block">Зарегистрироваться</button>
    </a>
    
</div>

</div>
{% endblock %}

shop/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<h3 class="mt-3 mb-3">Заказы пользователя {{ request.user.username }}</h3>
{% if not orders.count %}
<div class="col-md-12" style="margin-top: 300px; margin-bottom: 300px;">
    <h3>У вас еще нет заказов. <a href="{% url 'base' %}">Начните делать покупки</a></h3>
</div>
{% else %}
<div class="col-md-12" style="margin-top: 250px; margin-bottom: 250px;">
    <table class="table">
        <thead>
            <th scope="col">Номер</th>
            <th scope="col">Статус</th>
            <th scope="col">Сумма</th>
            <th scope="col">Товар</th>
            <th scope="col">Дополнительно</th>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">{{ order.id }}</th>
                    <td>{{ order.get_status_display }}</td>
                    <td>{{ order.cart.final_price }} руб.</td>
                    <td>
                        <ul>
                            {% for item in order.cart.products.all %}
                                <li>{{ item.content_object.title }} x {{ item.qty }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">Дополнительно</button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Детализация заказа</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    <h4 class="text-center">Товар</h4>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">Наименование</th>
                                                <th scope="col">Изображение</th>
                                                <th scope="col">Цена</th>
                                                <th scope="col">Кол-во</th>
                                                <th scope="col">Общая цена</th>
                                            </tr>
                                        </thead>   
                                        <tbody>
                                            {% for item in order.cart.products.all %}
                                                <tr>
                                                    <th scope="row">{{ item.content_object.title }}</th>
                                                    <td class="w-25"><img src="{{ item.content_object.image.url }}"  style="width: auto; max-height: 150px"  class="img-fluid rounded mx-auto d-block"></td>
                                                    <td><strong>{{ item.content_object.price }}</strong>руб.</td>
                                                    <td>{{ item.qty }}</td>
                                                    <td>{{ item.final_price }}</td>
                                                </tr>
                                            {% endfor %}
                                            <tr>
                                                <td colspan="2"></td>
                                                <td>Итого:</td>
                                                <td>{{ order.cart.total_products }}</td>
                                                <td><strong>{{ order.cart.final_price }}</strong>руб.</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <hr>
                                    <h4 class="text-center">Дополнительная информация</h4>
                                    <p>Имя: <strong>{{ order.first_name }}</strong></p>
                                    <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                                    <p>Телефон: <strong>{{ order.customer.phone }}</strong></p>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                </div>
                            </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}